### PR TITLE
Updated for 10.39.6.0 + new screenshot bypass

### PR DESCRIPTION
**Pull request by ghost**
Updated for 10.39.6.0 + new screenshot bypass

### CODE REVIEW

**Comment by georgeravenholm** [comment]
oh nice you figured it out!
how does it work lol

**Review by georgeravenholm — CHANGES_REQUESTED** [review]
probably not a good idea to nuke the readme file lol

**Comment by Alexey25322** [comment]
For anyone who can't wait, here is a worikng compiled updated version.

http://juckt.xyz/snapcept.apk

Make sure to update Snapchat to 10.39.6.0

**Comment by ghost** [comment]
There 💃

**Pull request merged**
